# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/gabrielssouza25/194c125de12625b6abb5de852aa306ce/untitled3.ipynb
"""

print("Programa que identifica o maior número digitado!\n")
n1 = input("Digite o primeiro número:\n")
n2 = input("Digite o primeiro número:\n")

if(n1 > n2):
  print(n1,"Número maior")
elif(n2 > n1):
  print(n2,"Número maior")

def vogal_ou_consoante(letra):
    letra = letra.lower()
    if letra in ('a', 'e', 'i', 'o', 'u'):
        return True
    elif letra in ('b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'v', 'w', 'x', 'y', 'z'):
        return False
print(vogal_ou_consoante('a')) # True
print(vogal_ou_consoante('c')) # False

num1 = int(input("Número um: "))
num2 = int(input("Número dois: "))
num3 = int(input("Número três: "))

if num1 > num2 and num3:
    print("O número um é o maior: ", num1)
elif num2 > num1 and num3:
    print("O número dois é o maior: ", num2)
elif num3 > num1 and num2:
    print("O número três é o maior: ", num3)

n1 = input('Digite o 1° numero: ')
n2 = input('Digite o 2° numero: ')
n3 = input('Digite o 3° numero: ')

def maior():
    if n1 > n2 and n3 and n1:
        print(n1, 'é o maior numero')
    elif n2 > n1 and n3:
        print(n2,'é o maior numero')
    elif n3 > n1 and n2:
        print(n3,'é o maior numero')

    #Se alguns numeros forem iguais

    elif n1 == n2 and n1 and n2 > n3:
        print (n1,'é','o maior!!')
    elif n1 == n3 and n1 and n3 > n2:
        print (n1,'é','o maior!!')
    elif n2 == n3 and n2 and n3 > n1:
        print (n2,'é','o maior!!')
    #todos os numeros iguais
    elif n1 == n2 and n3:
        print ('todos o numeros são iguais')

def menor():
    if n1 < n2 and n3 and n1:
        print (n1, 'é o menor numero!!')
    elif n2 < n1 and n3:
        print (n2,'é o menor numero!!')
    elif n3 < n1 and n2:
        print (n3,'é o menor numero!!')

    #Se alguns numeros forem iguais

    elif n1 == n2 and n1 and n2 < n3:
        print (n1,'é','o menor!!')
    elif n1 == n3 and n1 and n3 < n2:
        print (n1,'é','o menor!!')
    elif n2 == n3 and n2 and n3 < n1:
        print (n2,'é','o menor!!')

maior()   #chama metodo para descubrir o maior
menor()   #chama metodo para descubrir o menor

import time

print ('Bem vindo ao exercicio 8 da Estrutura de Desição')

time.sleep(0.8)
print ('-------------------------------------------------')
print ('')

p1 = input("Digite o 1° preço: ")
p2 = input("Digite o 2° preço: ")
p3 = input("Digite o 3° preço: ")

def menor():
    if p1 < p2 and p3 and p1:
        print ('O produto 1 é o mais barato!!')
    elif p2 < p1 and p3:
        print ('O produto 2 é o mais barato!!')
    elif p3 < p1 and p2:
        print ('O produto 3 é o mais barato!!')

    #Se alguns numeros forem iguais

    elif p1 == p2 and p1 and p2 < p3:
        print ('O produto 1 e 2 são os mais baratos!!')
    elif p1 == p3 and p1 and p3 < p2:
        print ('O produto 1 e 3 são os mais baratos!!')
    elif p2 == p3 and p2 and p3 < p1:
        print ('O produto 1 e 2 são os mais baratos!!')

    #Se todo os numero forem iguais

    else:
        print ('Todos os preços são iguais!!')

menor() # chama a função menor!

a = float(input('Escreva um número: '))
b = float(input('Escreva um número: '))
c = float(input('Escreva um número: '))

if a >= b and a >= c and b >= c:
    print(f'A ordem decrescente é {a} , {b} e {c}')
elif a >= b and a >=c and c >= b:
    print(f'A ordem decrescente é {a} , {c} e {b}')
elif b >= a and b >= c and a >= c:
    print(f'A ordem decrescente é {b} , {a} e {c}')
elif b >= a and b >= c and c >= a:
    print(f'A ordem decrescente é {b} , {c} e {a}')
elif c >= a and c >= b and a >=b:
    print(f'A ordem decrescente é {c} , {a} e {b}')
elif c >= a and c >= b and b >= a:
    print(f'A ordem decrescente é {c} , {b} e {a}')

# -*- coding: latin-1 -*-
turno = str(input('Digite em que turno você estuda: M=maturnino, V=vespertino ou N-noturno: ').upper())

if turno == 'M':
    print('Bom dia!')

elif turno == 'V':
    print('Boa tarde!')

elif turno == 'N':
    print('Boa noite!')

else:
    print('Valor inválido!')

